Controllers/ClassController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DeadNoteNew.Databases;
using DeadNoteNew.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace DeadNoteNew.Controllers
{
    public class ClassController : Controller
    {
        private readonly ApplicationDbContext _context;

        public INotyfService _notyfService { get; set; }
        public ClassController(ApplicationDbContext context,INotyfService notyfService)
        {   
            _notyfService = notyfService;
            _context = context;
        }

        /// <summary>
        /// Get all class which user take part in
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var uid = Request.Cookies["uid"];

            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);

            if (account == null) return Redirect("/Login");

            var accountClasses = _context.Classes.Where(c => c.Accounts.Any(a => a.Id == guid));

            ViewData["account"] = account;

            return View(accountClasses);
        }

        /// <summary>
        /// Delete class with specific id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var guid = Guid.Parse(id);

            var delClass = _context.Classes.Find(guid);
            if (delClass == null) return NotFound();

            var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == guid));

            ViewData["delClass"] = delClass;
            ViewData["members"] = members;

            return View();
        }

        /// <summary>
        /// Callback function after user submit delete form, check if user exists and perform delete
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult DeleteConfirmed(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var guid = Guid.Parse(id);

            var delClass = _context.Classes.Find(guid);
            if (delClass == null) return NotFound();

            delClass.Status = false;
            _context.Classes.Update(delClass);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Get form to create new class, only teacher can create class
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Register");

            // If user is not teacher redirect to /Class
            if (!account.IsTeacher) return RedirectToAction("Index");
            return View();
        }

        /// <summary>
        /// Callback function for create class, save class to database
        /// </summary>
        /// <param name="subject"></param>
        /// <param name="studentGroup"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create(string subject, string studentGroup)
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Login");

            // If user is not teacher redirect to /Class
            if (!account.IsTeacher) return RedirectToAction("Index");

            // Create class name with subject and student group
            if (string.IsNullOrEmpty(subject) || string.IsNullOrEmpty(studentGroup)) return BadRequest();
            var className = $"{subject}_{studentGroup}";

            // Class name exist
            if (_context.Classes.Any(c => c.Name == className))
            {
                ViewData["classNameExist"] = $"{className} already exist.";
                return View("Create");
            }
            
            var newClass = new Class { Id = Guid.NewGuid(), Name = className, Status = true };
            newClass.Accounts.Add(account);
            
            _context.Classes.Add(newClass);
            _context.SaveChanges();
            _notyfService.Success("Create class success");
            return RedirectToAction("Index");
        }

        // /// <summary>
        // /// Leave class, remove the link between student and that class
        // /// </summary>
        // /// <param name="id"></param>
        // /// <returns></returns>
        // public IActionResult Leave(Guid id)
        // {   
        //     var uid = Request.Cookies["uid"];

        //     if (!Utils.CheckGuid(uid)) return Redirect("/Login");

        //     var guid = Guid.Parse(uid);
        //     var account = _context.Accounts.Find(guid);
        //     if (account == null) return Redirect("/Login");

        //     var leavingClass = _context.Classes.Find(id);
        //     if (leavingClass == null) return NotFound();

        //     var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == id));

        //     ViewData["leavingClass"] = leavingClass;
        //     ViewData["members"] = members;
        //     TempData["classID"] = leavingClass.Id;
        //     return View();
        // }

        // /// <summary>
        // /// Return View for user to confirm leaving class
        // /// </summary>
        // /// <param name="id">ID of the class user want to leave</param>
        // /// <returns></returns>
        // [HttpPost]
        // public async Task<IActionResult> Leave(Guid? id)
        // {   
        //     var uid = Request.Cookies["uid"];

        //     if (!Utils.CheckGuid(uid)) return Redirect("/Login");

        //     var guid = Guid.Parse(uid);
        //     var account = _context.Accounts.Find(guid);
        //     if (account == null) return Redirect("/Login");

        //     var leavingClass = _context.Classes.Find(id);
        //     if (leavingClass == null) return NotFound();

        //     // var member = this._context.Classes.Include(a => a.Accounts).SingleOrDefault(a => a.Id == account.Id);
        //     var member = _context.Accounts.FirstOrDefault(a => a.Classes.Any(c => c.Id == id));

        //     leavingClass.Accounts.Remove(member);
        //     _context.Update(leavingClass);
        //     await _context.SaveChangesAsync();
        //     return RedirectToAction("Index");
        // }
    }
}

Controllers/MemberController.cs
using System;
using System.Linq;
using DeadNoteNew.Databases;
using Microsoft.AspNetCore.Mvc;
using DeadNoteNew.Models;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace DeadNoteNew.Controllers
{
    public class MemberController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notyfService;

        public MemberController(ApplicationDbContext context, INotyfService notyfService)
        {
            _notyfService = notyfService;
            _context = context;
        }

        /// <summary>
        /// Show list of member in class
        /// </summary>
        /// <param name="id">Required, ID of class to show member</param>
        /// <returns>Member in that class</returns>
        public IActionResult Index(Guid id)
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Login");

            var foundClass = _context.Classes.Find(id);
            if (foundClass == null) return Redirect("/Class");

            var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == id));

            ViewData["foundClass"] = foundClass;
            ViewData["members"] = members;
            ViewData["isTeacher"] = account.IsTeacher;

            return View();
        }

        /// <summary>
        /// Add member to class
        /// </summary>
        /// <returns></returns>
        public IActionResult AddMember(Guid id)
        {
            TempData["classId"] = id;
            return View();
        }

        /// <summary>
        /// Callback function to add member
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult AddMember(Guid classId, Guid memberId)
        {
            var member = _context.Accounts.FirstOrDefault(a => a.Id == memberId);
            if (member == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            var foundClass = _context.Classes.SingleOrDefault(c => c.Id == classId);
            foundClass.Accounts.Add(member);
            _context.SaveChanges();
            return RedirectToAction("Index", classId);
        }

        /// <summary>
        /// Return View to confirm delete member in class
        /// </summary>
        /// <returns></returns>
        [HttpGet("Member/Delete/{classId}/{memberId}")]
        public IActionResult Delete(Guid memberId, Guid classId)
        {
            if (memberId == null || classId == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            var member = _context.Accounts.SingleOrDefault(a => a.Id == memberId);
            if (member == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            ViewData["classId"] = classId;

            return View(member);
        }

        /// <summary>
        /// Callback function to delete member in class
        /// </summary>
        /// <param name="memberId">Member to delete</param>
        /// <param name="classId">Class to be delete member</param>
        /// <returns></returns>
        [HttpPost("Member/Delete")]

        public IActionResult DeleteMember(string classId, Guid memberId)
        {
            // var foundClass = _context.Classes.Find(Guid.Parse(classId));

            var foundClass = this._context.Classes.Include(a => a.Accounts).SingleOrDefault(a => a.Id == Guid.Parse(classId));
            if (foundClass == null)
            {
                _notyfService.Error("Class not found!!");
                return View();
            }

            var member = _context.Accounts.Find(memberId);
            if (member == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            foundClass.Accounts.Remove(member);
            _context.Update(foundClass);
            _context.SaveChanges();



            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}

@if (!string.IsNullOrEmpty(message))
{
    <div class="alert alert-success p-0 alert-dismissible text-center fade show" role="alert">
        @TempData["StatusMessage"]
        <button type="button" class="close btn btn-sm" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>DeadNote</title>
    <link rel="icon" type="image/x-icon" href="~/DeadNote/assets/DeadNote.ico"/>
    <!-- Font Awesome icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
        rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/DeadNote/css/styles.css" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-action="Index">DeadNote</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Home"
                            asp-action="Index"> Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Class"
                            asp-action="Index">Class</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Deadline"
                            asp-action="Index">DeadLine</a></li>
                    @* <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Member"
                            asp-action="Index">Member</a></li> *@
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Home"
                            asp-action="About">About</a></li>
                            
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('/DeadNote/assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>DeadNote</h1>
                        <span class="subheading">Start Your New DeadLine!</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    @RenderBody();
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">

                                <i class="fab fa-facebook-f"></i>

                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">


                                <i class="fab fa-github"></i>

                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; DeadNote Website 2021</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/DeadNote/js/scripts.js"></script>
    <!--JQuery-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>

</html>
@await Component.InvokeAsync("Notyf")
@await RenderSectionAsync("Scripts", required: false)