Controllers/ClassController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DeadNoteNew.Databases;
using DeadNoteNew.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace DeadNoteNew.Controllers
{
    public class ClassController : Controller
    {
        private readonly ApplicationDbContext _context;

        public INotyfService _notyfService { get; set; }
        public ClassController(ApplicationDbContext context,INotyfService notyfService)
        {   
            _notyfService = notyfService;
            _context = context;
        }

        /// <summary>
        /// Get all class which user take part in
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var uid = Request.Cookies["uid"];

            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);

            if (account == null) return Redirect("/Login");

            var accountClasses = _context.Classes.Where(c => c.Accounts.Any(a => a.Id == guid));

            ViewData["account"] = account;

            return View(accountClasses);
        }

        /// <summary>
        /// Delete class with specific id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var guid = Guid.Parse(id);

            var delClass = _context.Classes.Find(guid);
            if (delClass == null) return NotFound();

            var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == guid));

            ViewData["delClass"] = delClass;
            ViewData["members"] = members;

            return View();
        }

        /// <summary>
        /// Callback function after user submit delete form, check if user exists and perform delete
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult DeleteConfirmed(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var guid = Guid.Parse(id);

            var delClass = _context.Classes.Find(guid);
            if (delClass == null) return NotFound();

            delClass.Status = false;
            _context.Classes.Update(delClass);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Get form to create new class, only teacher can create class
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Register");

            // If user is not teacher redirect to /Class
            if (!account.IsTeacher) return RedirectToAction("Index");
            return View();
        }

        /// <summary>
        /// Callback function for create class, save class to database
        /// </summary>
        /// <param name="subject"></param>
        /// <param name="studentGroup"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create(string subject, string studentGroup)
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Login");

            // If user is not teacher redirect to /Class
            if (!account.IsTeacher) return RedirectToAction("Index");

            // Create class name with subject and student group
            if (string.IsNullOrEmpty(subject) || string.IsNullOrEmpty(studentGroup)) return BadRequest();
            var className = $"{subject}_{studentGroup}";

            // Class name exist
            if (_context.Classes.Any(c => c.Name == className))
            {
                ViewData["classNameExist"] = $"{className} already exist.";
                return View("Create");
            }
            
            var newClass = new Class { Id = Guid.NewGuid(), Name = className, Status = true };
            newClass.Accounts.Add(account);
            
            _context.Classes.Add(newClass);
            _context.SaveChanges();
            _notyfService.Success("Create class success");
            return RedirectToAction("Index");
        }

        // /// <summary>
        // /// Leave class, remove the link between student and that class
        // /// </summary>
        // /// <param name="id"></param>
        // /// <returns></returns>
        // public IActionResult Leave(Guid id)
        // {   
        //     var uid = Request.Cookies["uid"];

        //     if (!Utils.CheckGuid(uid)) return Redirect("/Login");

        //     var guid = Guid.Parse(uid);
        //     var account = _context.Accounts.Find(guid);
        //     if (account == null) return Redirect("/Login");

        //     var leavingClass = _context.Classes.Find(id);
        //     if (leavingClass == null) return NotFound();

        //     var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == id));

        //     ViewData["leavingClass"] = leavingClass;
        //     ViewData["members"] = members;
        //     TempData["classID"] = leavingClass.Id;
        //     return View();
        // }

        // /// <summary>
        // /// Return View for user to confirm leaving class
        // /// </summary>
        // /// <param name="id">ID of the class user want to leave</param>
        // /// <returns></returns>
        // [HttpPost]
        // public async Task<IActionResult> Leave(Guid? id)
        // {   
        //     var uid = Request.Cookies["uid"];

        //     if (!Utils.CheckGuid(uid)) return Redirect("/Login");

        //     var guid = Guid.Parse(uid);
        //     var account = _context.Accounts.Find(guid);
        //     if (account == null) return Redirect("/Login");

        //     var leavingClass = _context.Classes.Find(id);
        //     if (leavingClass == null) return NotFound();

        //     // var member = this._context.Classes.Include(a => a.Accounts).SingleOrDefault(a => a.Id == account.Id);
        //     var member = _context.Accounts.FirstOrDefault(a => a.Classes.Any(c => c.Id == id));

        //     leavingClass.Accounts.Remove(member);
        //     _context.Update(leavingClass);
        //     await _context.SaveChangesAsync();
        //     return RedirectToAction("Index");
        // }
    }
}

Controllers/JoinController.cs
using System;
using DeadNoteNew.Databases;
using Microsoft.AspNetCore.Mvc;

namespace DeadNoteNew.Controllers
{
    public class JoinController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JoinController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Show form to take user input
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);

            if (account == null) return Redirect("/Register");
            return View();
        }
        

        /// <summary>
        /// Callback function to join class, if user joined that class, redirect to Class controller,
        ///  else create a link between user and that class
        /// </summary>
        /// <param name="classId"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Index(string classId)
        {
            if (string.IsNullOrEmpty(classId)) return NotFound();

            var parsedId = Guid.Parse(classId);
            var foundClass = _context.Classes.Find(parsedId);

            if (foundClass == null) return NotFound();

            var uid = Request.Cookies["uid"];
            if (string.IsNullOrEmpty(uid))
            {
                return Redirect("/Login");
            }

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Register");

            // User already in that class
            if (foundClass.Accounts.Contains(account)) return Redirect("/Class");

            foundClass.Accounts.Add(account);
            _context.SaveChanges();
            return Redirect("/Class");
        }
    }
}

Controllers/MemberController.cs
using System;
using System.Linq;
using DeadNoteNew.Databases;
using Microsoft.AspNetCore.Mvc;
using DeadNoteNew.Models;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace DeadNoteNew.Controllers
{
    public class MemberController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notyfService;

        public MemberController(ApplicationDbContext context, INotyfService notyfService)
        {
            _notyfService = notyfService;
            _context = context;
        }

        /// <summary>
        /// Show list of member in class
        /// </summary>
        /// <param name="id">Required, ID of class to show member</param>
        /// <returns>Member in that class</returns>
        public IActionResult Index(Guid id)
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Login");

            var foundClass = _context.Classes.Find(id);
            if (foundClass == null) return Redirect("/Class");

            var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == id));

            ViewData["foundClass"] = foundClass;
            ViewData["members"] = members;
            ViewData["isTeacher"] = account.IsTeacher;

            return View();
        }

        /// <summary>
        /// Add member to class
        /// </summary>
        /// <returns></returns>
        public IActionResult AddMember(Guid id)
        {
            TempData["classId"] = id;
            return View();
        }

        /// <summary>
        /// Callback function to add member
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult AddMember(Guid classId, Guid memberId)
        {
            var member = _context.Accounts.FirstOrDefault(a => a.Id == memberId);
            if (member == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            var foundClass = _context.Classes.SingleOrDefault(c => c.Id == classId);
            foundClass.Accounts.Add(member);
            _context.SaveChanges();
            return RedirectToAction("Index", classId);
        }

        /// <summary>
        /// Return View to confirm delete member in class
        /// </summary>
        /// <returns></returns>
        [HttpGet("Member/Delete/{classId}/{memberId}")]
        public IActionResult Delete(Guid memberId, Guid classId)
        {
            if (memberId == null || classId == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            var member = _context.Accounts.SingleOrDefault(a => a.Id == memberId);
            if (member == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            ViewData["classId"] = classId;

            return View(member);
        }

        /// <summary>
        /// Callback function to delete member in class
        /// </summary>
        /// <param name="memberId">Member to delete</param>
        /// <param name="classId">Class to be delete member</param>
        /// <returns></returns>
        [HttpPost("Member/Delete")]

        public IActionResult DeleteMember(string classId, Guid memberId)
        {
            // var foundClass = _context.Classes.Find(Guid.Parse(classId));

            var foundClass = this._context.Classes.Include(a => a.Accounts).SingleOrDefault(a => a.Id == Guid.Parse(classId));
            if (foundClass == null)
            {
                _notyfService.Error("Class not found!!");
                return View();
            }

            var member = _context.Accounts.Find(memberId);
            if (member == null)
            {
                _notyfService.Error("Member not found!!");
                return View();
            }

            foundClass.Accounts.Remove(member);
            _context.Update(foundClass);
            _context.SaveChanges();



            return RedirectToAction("Index");
        }
    }
}

Views/Class/Create.cshtml
@model Class

@{

    ViewData["Title"] = "Create Class";

    var classNameExist = ViewData["classNameExist"];
}

<h1 class="text-center">Create new class</h1>

<form asp-action="Create" method="POST">
    <div class="row justify-content-center">

        <div class="form-group col-8">
            <label for="subject">Subject: </label>
            <input type="text" class="form-control" id="subject" name="subject" placeholder="Ex: SWP391" required>
        </div>
        <div class="form-group col-8 mt-3">
            <label for="student-group">Student group: </label>
            <input type="text" class="form-control" id="student-group" name="studentGroup" placeholder="Ex: SE1504"
                required>
        </div>

    </div>

    @if (classNameExist != null)

    {
        <p class="text-center text-danger mt-3">@classNameExist</p>

    }

    <div class="row justify-content-center mt-3">
        <input class="btn col-sm-5 btn-primary" type="submit" value="Create">
    </div>
</form>

Views/Class/Delete.cshtml
@{
    ViewData["Title"] = "Delete Class";
    var delClass = ViewData["delClass"] as Class;
    var members = ViewData["members"] as IQueryable<Account>;
}

<h1 class="display-4 text-center">Delete Class: @delClass.Name</h1>

<table class="table table-bordered table-hover table-striped">
    <caption class="text-center">Members in class</caption>
    <thead class="thead-dark">
    <th>ID</th>
    <th>Email</th>
    <th>Full Name</th>
    <th>Gender</th>
    <th>Birthday</th>
    <th>Address</th>
    </thead>

    <tbody>
    @foreach (var member in members)
    {
        <tr>
            <td>@member.Id</td>
            <td>@member.Email</td>
            <td>@member.FullName</td>
            <td>@member.Gender</td>
            <td>@member.Birthday</td>
            <td>@member.Address</td>
        </tr>
    }
    </tbody>
</table>

<h3 class="text-danger text-center">Do you really want to delete this class?</h3>
<h5 class="text-danger text-center">This action cannot be undo!</h5>

<div class="row justify-content-center">
    <a asp-action="DeleteConfirmed" asp-route-id="@delClass.Id" class="btn btn-danger w-25 mt-3 mb-3">Delete</a>
</div>
<div class="row justify-content-center">
    <a href="/Class" class="btn btn-primary w-25">Cancel</a>
</div>

Views/Class/Index.cshtml
@model IQueryable<Class>

@{
    ViewData["Title"] = "Classes";
    var account = ViewData["account"] as Account;
}
<div class="container">
@if (account is {IsTeacher: true })
{
    <a class="btn btn-block btn-info mb-3" asp-action="Create">Create Class</a>
}
else
{
    <a class="btn btn-block btn-primary mb-3" asp-controller="Join">Join Class</a>
}
<div class="row">
    @foreach (var item in Model)
      {
        @if (!item.Status) continue;
                        <div class="pt-5 m-auto">                          
                                <div class="card card-custom bg-white border-white border-0">
                                    <div class="card-custom-img"
                                    style="background-image: url(http://res.cloudinary.com/d3/image/upload/c_scale,q_auto:good,w_1110/trianglify-v1-cs85g_cc5d2i.jpg);">
                                    </div>
                                    <div class="card-custom-avatar">
                                        <img class="img-fluid"
                                        src="~/DeadNote/assets/Traidat.png"
                                        alt="Avatar" />
                                    </div>
                                    <div class="card-body" style="overflow-y: auto">
                                        <h4 class="card-title">@item.Name</h4>
                                        <p class="card-text"> ID : <br>@item.Id.ToString().ToUpper()  
                                    </div>
                                        <div class="text-center mb-2">
                                        <a class="btn btn-primary" asp-controller="Deadline" asp-action="Class" asp-route-id="@item.Id">Deadlines</a>
                                        <a class="btn btn-info" asp-controller="Member" asp-route-id="@item.Id">Members</a>
                                        @if (account is {IsTeacher: true}){
                                             <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        } 
                                        @* else {
                                            <a class="btn btn-danger" asp-action="Leave" asp-route-id="@item.Id">Leave</a>
                                        } *@
                                    </div>
                                </div>
                            </div>
          
     }
     </div>
</div>

  <style>
            .card-custom {
                        overflow: hidden;
                        min-height: 450px;
                        box-shadow: 0 0 15px rgba(10, 10, 10, 0.3);
                        }

            .card-custom-img {
            height: 200px;
            min-height: 200px;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            border-color: inherit;
            }

            /* First border-left-width setting is a fallback */
            .card-custom-img::after {
            position: absolute;
            content: '';
            top: 161px;
            left: 0;
            width: 0;
            height: 0;
            border-style: solid;
            border-top-width: 40px;
            border-right-width: 0;
            border-bottom-width: 0;
            border-left-width: 545px;
            border-left-width: calc(575px - 5vw);
            border-top-color: transparent;
            border-right-color: transparent;
            border-bottom-color: transparent;
            border-left-color: inherit;
            }

            .card-custom-avatar img {
            border-radius: 50%;
            box-shadow: 0 0 15px rgba(10, 10, 10, 0.3);
            position: absolute;
            top: 100px;
            left: 1.25rem;
            width: 100px;
            height: 100px;
            }
  </style>

Views/Class/Leave.cshtml
@{
    ViewData["Title"] = "Leave Class";
    var leavingClass = ViewData["leaveClass"] as Class;
    var members = ViewData["members"] as IQueryable<Account>;
    var leadvingClass1 = TempData["classID"] ;
}

<h1 class="text-center display-4">Leave Class: @leavingClass?.Name</h1>

<table class="table table-bordered table-hover table-striped">
    <caption class="text-center">Members in class</caption>
    <thead class="thead-dark">
    <th>ID</th>
    <th>Email</th>
    <th>Full Name</th>
    <th>Gender</th>
    <th>Birthday</th>
    <th>Address</th>
    </thead>

    <tbody>
    @foreach (var member in members)
    {
        <tr>
            <td>@member.Id</td>
            <td>@member.Email</td>
            <td>@member.FullName</td>
            <td>@member.Gender</td>
            <td>@member.Birthday</td>
            <td>@member.Address</td>
        </tr>
    }
    </tbody>
</table>

<h3 class="text-danger text-center">Do you really want to leave this class?</h3>
<form method="post" asp-action="Leave" asp-route-id="@leadvingClass1">
<input type="submit"  value="Leave" class="btn btn-danger btn-block mt-3 mb-3"/>
<a href="/Class" class="btn btn-primary btn-block">Cancel</a>
</form>